version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
